feat: added FrameWallet
MASQ-Project/MASQ-web3-dapp-store pull request #10
Opened 2023-01-29 21:17 UTC by FinsaasGH

2023-02-01 01:04 UTC, kauri-hero commented on configs/dapps.js
> +      },
going to add to the `Discover` category also to showcase Frame wallet when users first head to dApp Library

2023-02-01 01:04 UTC, kauri-hero approved these changes

2023-02-01 01:07 UTC, kauri-hero requested changes
sorry my last review I selected 'Approve'

please see small adjustment for `dapps.js`

2023-02-01 07:48 UTC, kauri-hero requested changes
just simple name change

2023-02-01 07:48 UTC, kauri-hero commented on configs/dapps.js
> +        name: 'FrameWallet',
Sorry one last change - can you change name to just 'Frame'

2023-02-01 07:48 UTC, kauri-hero commented on configs/dapps.js
> +        name: 'FrameWallet',
Same here please

2023-02-02 03:20 UTC, FinsaasGH commented
changes completed

2023-02-02 23:19 UTC, kauri-hero approved these changes

2023-02-02 23:19 UTC, merged