add: pegaxy
MASQ-Project/MASQ-web3-dapp-store pull request #28
Opened 2023-09-14 03:09 UTC by FinsaasGH

2023-09-14 22:22 UTC, kauri-hero requested changes

2023-09-14 22:22 UTC, kauri-hero commented on configs/dapps.js
> +        name: 'Pregaxy',
Please correct title to "Pegaxy"

2023-09-15 00:49 UTC, FinsaasGH commented
Typo resolved

2023-09-16 22:56 UTC, kauri-hero approved these changes

2023-09-16 22:56 UTC, merged